Controllers films users
greblovp/java-filmorate pull request #2
Opened 2023-03-09 19:52 UTC by greblovp

2023-03-10 18:15 UTC, mikita95 requested changes
Все сделано отлично :) Нужно только поправить пару моментов.

2023-03-10 18:15 UTC, mikita95 commented on HELP.md
> +
Этот файл - общий. Лучше заменить его на README.md и просто коротко описать проект

2023-03-10 18:15 UTC, mikita95 commented on pom.xml
> +			<version>1.18.20</version>
Лучше выносить номер версий в свойства - так проще управлять и отслеживать зависимости

2023-03-10 18:15 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmRepository.java
> +public class FilmRepository {
Как вариант, можно вынести общий абстрактный репозиторий, так как `FilmRepository` и `UserRepository` очень похожи

2023-03-10 18:15 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Нужно еще добавить юнит-тесты на контроллеры

2023-03-11 18:06 UTC, greblovp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Добавил тесты

2023-03-11 18:06 UTC, greblovp commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmRepository.java
> +public class FilmRepository {
Добавил абстрактные классы и наследование

2023-03-11 18:07 UTC, greblovp commented on pom.xml
> +			<version>1.18.20</version>
Вынес номер версии в свойства

2023-03-11 18:07 UTC, greblovp commented on HELP.md
> +
Поправил

2023-03-12 09:18 UTC, mikita95 approved these changes
Все отлично :) Можно смержить пул-реквест

2023-03-12 11:31 UTC, merged