Add database
greblovp/java-filmorate pull request #4
Opened 2023-04-17 15:20 UTC by greblovp

2023-04-18 19:11 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь пару небольших замечаний

2023-04-18 19:11 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        Set<Genre> genres = genreIds.stream()
Можно заинлайнить переменную

2023-04-18 19:11 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/BaseModel.java
> +    BaseModel() {
Можно использовать аннотацию`@NoArgsConstructor`

2023-04-18 19:11 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        jdbcTemplate.update(sqlQuery, film.getId(), user.getId());
Получается, что если попытаться для одного пользователя поставить второй лайк на один фильм, то здесь вылетил ошибка

2023-04-18 19:33 UTC, greblovp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        jdbcTemplate.update(sqlQuery, film.getId(), user.getId());
Да, СУБД не даст провести транзакцию - выдаст ошибку о нарушении первичного ключа. При этом логика работы Java приложения будет корректной - запрос отрабатывает, приложение не падает, а транслирует ошибку из БД вовне, лишние записи в БД не создаются.
Нужно дополнительно обработать ошибку (исключение) в Java? переписать во что-то более информативное?  Или на уровне Java приложения необходимо сделать защиту от подобных действий - проверять, что передаваемый ключ уже существует в бд и не пытаться заинсертить его снова?

2023-04-18 20:03 UTC, greblovp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        jdbcTemplate.update(sqlQuery, film.getId(), user.getId());
Могу добавить в Сервисы обработку исключения DataIntegrityViolationException - подменять его на кастомное исключение FilmAlreadyLikedException и UserAlreadyHasFriend. Далее эти кастомные исключения дополнительно обработать в ErrorHandler через @ExceptionHandler

2023-04-18 21:18 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        jdbcTemplate.update(sqlQuery, film.getId(), user.getId());
Предполагается, что метод PUT (в данном случае addLike) должен быть идемпотентным (то есть несколько вызовов одного и того же метода с одними параметрами, имеет такой же эффект как и один вызов). В данном случае можно просто поменять sql-запрос, использовав команду merge в H2 (https://www.h2database.com/html/commands.html#merge_into) - если запись существует, то это сработает как update, иначе произойдет insert.

2023-04-18 21:28 UTC, greblovp commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        jdbcTemplate.update(sqlQuery, film.getId(), user.getId());
Принято, откатываю обратно 😂

2023-04-19 19:05 UTC, mikita95 approved these changes
Все сделано отлично. Можно мержить пул-реквест.

2023-04-19 19:51 UTC, merged